name: CI

on:
  push:
    paths:
      - '.github/**'
      - 'img/**'
      - 'data.js'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: npm install and build
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/StegSchreck/uberpage/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
        wget https://github.com/StegSchreck/uberpage/archive/${LATEST_VERSION}.tar.gz || exit
        mkdir -p uberpage
        tar -xf ${LATEST_VERSION}.tar.gz -C uberpage --strip-components 1
        rm -f ${LATEST_VERSION}.tar.gz

        rm -rf static precache-manifest*

        cp -f data.js uberpage/uberpage/src/data.js
        cd uberpage/uberpage
        find public/img -not -iname "*uberpage*" -type f -delete
        npm install -g npm@latest
        npm ci
        ../scripts/adjust_homepage.sh "https://wischlabs.github.io"
        npm run build
      env:
        CI: true
    - name: GitHub Pages Deploy
      uses: crazy-max/ghaction-github-pages@v1.2.5
      if: success() && github.ref == 'refs/heads/master'
      with:
        # Git branch where assets will be deployed
        target_branch: master
        # Create incremental commit instead of doing push force
        keep_history: true
        # Build directory to deploy
        build_dir: uberpage/uberpage/build
        # Write the given domain name to the CNAME file
        #fqdn: stegschreck.github.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
