name: CI

on:
  push:
    paths:
      - '.github/**'
      - 'img/**'
      - 'data.js'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: npm install and build
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/StegSchreck/uberpage/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
        wget https://github.com/StegSchreck/uberpage/archive/${LATEST_VERSION}.tar.gz || exit
        mkdir -p uberpage
        tar -xf ${LATEST_VERSION}.tar.gz -C uberpage --strip-components 1
        rm -f ${LATEST_VERSION}.tar.gz

        rm -rf static precache-manifest*

        cp -f data.js uberpage/uberpage/src/data.js
        cd uberpage/uberpage
        find public/img -not -iname "*uberpage*" -type f -delete
        npm install -g npm@latest
        npm ci
        ../scripts/adjust_homepage.sh "https://wischlabs.github.io"
        npm run build
      env:
        CI: true
    - name: Deploy GitHub Pages site
      uses: JamesIves/github-pages-deploy-action@v4
      if: github.ref_name == 'master'
      with:
        # GitHub repository where assets will be deployed (default current)
        repository-name: StegSchreck/stegschreck.github.io
        # Git branch where assets will be deployed
        branch: master
        # delete files from your deployment destination that no longer exist in your deployment source
        clean: true
        # Build directory to deploy
        folder: uberpage/build
        token: ${{ secrets.GHA_PAT }}
